spring.application.name=El_Telon

spring.datasource.url=jdbc:mysql://localhost:3306/el_telon_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Lalunaeshermosa12

spring.jpa.hibernate.ddl-auto=none

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-on-migrate=false

spring.web.error.include-message=always

jwt.secret.key=${SECRET_KEY}
