spring.application.name=El_Telon

spring.datasource.url=jdbc:mysql://localhost:3306/el_telon_db
spring.datasource.username=root
spring.datasource.password=admin123

spring.jpa.hibernate.ddl-auto=none

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.web.error.include-message=always

jwt.secret.key=${SECRET_KEY}
